services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - '${ELASTIC_PORT}:${ELASTIC_PORT}'
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://{PROJECT_NAME}:{ELASTIC_PORT}
      - ELASTICSEARCH_USERNAME={KIBANA_USERNAME}
      - ELASTICSEARCH_PASSWORD={KIBANA_PASSWORD}
    ports:
      - '${KIBANA_PORT}:${KIBANA_PORT}'
    depends_on:
      - elasticsearch
    networks:
      - elastic
volumes:
  es_data:
    driver: local
networks:
  elastic:
    name: elastic
    driver: bridge